version: '3.4'

networks:
    myAppNetwork:         

services:
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=123456
    endpoint.api:
        container_name: WebApiContainer
        image: ${DOCKER_REGISTRY-}endpointapi
        ports:
            - 8001:80 
        build:
          context: .
          dockerfile: EndPoint.Api/Dockerfile
        depends_on:
            - SqlServerDb